# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            Capelo is blogging
tagline:          ''
description:      'thoughts on coding / sampling / analog photography / rest of life'
url:              http://blog.antoniocapelo.com
baseurl:          '/'
paginate:         5

author:
  name:           'Ant√≥nio Capelo'
  url:            https://twitter.com/antoniocapelo
  twitter:		  antoniocapelo

# Custom vars
version:          1.0.0

github:           https://github.com/antoniocapelo/

homepage:		  http://www.capelo.me
homepageName:		  capelo.me

rssfeed:		  http://feeds.feedburner.com/CapeloIsBlogging